# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate log of Gaussian distribution function accurately
#' 
#' This function returns the probability of a standard Gaussian variate between 
#' the interval \code{a} and \code{b}, avoiding numerical overflow. The function is vectorized
#' and is meant to be used only internally by the package \code{TruncatedNormal}.
#' 
#' @param a vector of lower bound
#' @param b vector of upper bound
#' @param check logical; should checks be performed? 
#' @return a vector of log probability.
#' @keywords internal
#' @useDynLib TruncatedNormal
#' @importFrom Rcpp evalCpp
lnNpr <- function(a, b, check = FALSE) {
    .Call('_TruncatedNormal_lnNpr', PACKAGE = 'TruncatedNormal', a, b, check)
}

#' Cholesky matrix decomposition with GGE ordering
#' 
#' This function computes the Cholesky decomposition of a covariance matrix
#' \code{Sigma} and returns a list containing the permuted bounds for integration. 
#' The prioritization of the variables follow the rule proposed in Gibson, Glasbey and Elston (1994)
#' and reorder variables to have outermost variables with smallest expected values.
#' 
#' The list contains an integer vector \code{perm} with the indices of the permutation, which is such that
#' \code{Sigma(perm, perm) == L \%*\% t(L)}.
#' The permutation scheme is described in Genz and Bretz (2009) in Section 4.1.3, p.37.
#' @param Sigma \code{d} by \code{d} covariance matrix
#' @param l \code{d} vector of lower bounds
#' @param u \code{d} vector of upper bounds
#' @return a list with components
#' \itemize{
#' \item{\code{L}: }{Cholesky root}
#' \item{\code{l}: }{permuted vector of lower bounds}
#' \item{\code{u}: }{permuted vector of upper bounds}
#' \item{\code{perm}: }{vector of integers with ordering of permutation}
#' }
#' @references Genz, A. and Bretz, F. (2009). Computations of Multivariate Normal and t Probabilities, volume 105. Springer, Dordrecht.
#' @references Gibson G.J., Glasbey C.A. and D.A. Elton (1994).  Monte Carlo evaluation of multivariate normal integrals and sensitivity to variate ordering. In: Dimon et al., Advances in Numerical Methods and Applications, WSP, pp. 120-126.
cholperm <- function(Sigma, l, u) {
    .Call('_TruncatedNormal_cholperm', PACKAGE = 'TruncatedNormal', Sigma, l, u)
}

#' Return quantile of truncated Gaussian
#' 
#' The function compute the \code{p}th quantile associated to the truncated standard Gaussian 
#' variate on the interval (\code{l},\code{u}).
#' 
#' @param p vector of probabilities
#' @param l \code{d} vector of lower bounds
#' @param u \code{d} vector of upper bounds
#' @return vector of quantiles
#' @keywords internal
Phinv <- function(p, l, u) {
    .Call('_TruncatedNormal_Phinv', PACKAGE = 'TruncatedNormal', p, l, u)
}

